Page({
    data: {
        bannerList:{
            config:{
                indicatorDots: false,
                autoplay: true,
                interval: 2000,
                duration: 1000
            },
            items:[
                {
                    id:'1',
                    tag:'想去二周年',
                    src:'http://xqproduct.xiangqu.com/FvKbCMBX3mjJR9h5BzP-GiphSNjI?imageView2/2/w/770/q/90/format/jpg/770x360/',
                    mode:'aspectFit'
                },
                {
                    id:'2',
                    tag:'美式街头的不屑',
                    src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                    mode:'aspectFit'
                },
                {
                    id:'3',
                    tag:'美物与慢生活',
                    src:'http://xqproduct.xiangqu.com/FoBcb049nGf-HXLXE1hr3fKVaB0k?imageView2/2/w/770/q/90/format/jpg/770x360/',
                    mode:'aspectFit'
                },
            ],
            texts:[
                '原创设计师',
                '传统手工艺制作',
                '精选小众美物',
            ],
        },
        productList:[
            {
                tag:'精选',
                items:[
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'99',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'98',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'97',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'96',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'95',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'94',
                        name:'想去好设计',
                        link:'product'
                    },
                ]
            },
            {
                tag:'推荐',
                items:[
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'99',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'98',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'97',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'96',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'95',
                        name:'想去好设计',
                        link:'product'
                    },
                    {
                        src:'http://xqproduct.xiangqu.com/FiZLUkRyq2Nr_QzrcodaHtlpDYYe?imageView2/2/w/770/q/90/format/jpg/770x360/',
                        mode:'aspectFit',
                        price:'94',
                        name:'想去好设计',
                        link:'product'
                    },
                ]
            },
        ]
    },
})